plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.example.isoterm'
    compileSdk 36

    defaultConfig {
        applicationId 'com.example.isoterm'
        minSdk 28
        targetSdk 36
        versionCode 1
        versionName '1.0'
        ndk {
            abiFilters 'arm64-v8a'
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.lifecycle:lifecycle-service:2.8.7'
    // Правильно по wiki https://github.com/termux/termux-app/wiki/Termux-Libraries
    // group = com.termux.termux-app (не com.github...), триггер: https://github.com/termux/termux-app/blob/master/.github/workflows/trigger_library_builds_on_jitpack.yml
    implementation 'com.termux.termux-app:terminal-view:0.118.0'
    implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'
}
